spring:
  application:
    name: midgard-backend-template
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: local

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
